# K9log - Engineering-grade Causal Audit for AI Agent Ecosystems
# Copyright (C) 2026 Haotian Liu
# AGPL-3.0
"""
K9log LLM-Assisted AGENTS.md Parser
=====================================
Uses Claude to parse natural language rules from AGENTS.md into
structured K9Audit constraints, then validates the result with
deterministic smoke tests before saving.

Flow:
    AGENTS.md (natural language)
        ↓ Claude parses
    constraints JSON (draft)
        ↓ schema validation + smoke tests
    verified constraints
        ↓ SHA256 hash
    Y*_t intent contract (deterministic, tamper-proof)

Usage:
    from k9log.agents_md_llm import parse_agents_md_with_llm
    result = parse_agents_md_with_llm("~/.openclaw/workspace/AGENTS.md")
    if result.verified:
        # save to ~/.k9log/config/
        result.save()

Boundary declaration:
    Constraints are generated by Claude from AGENTS.md, then
    verified by deterministic schema validation and smoke tests.
    Once saved, constraints are hashed into the CIEU chain and
    become fully deterministic. If the parsed result seems wrong,
    manually edit ~/.k9log/config/{skill}.json.
"""
from __future__ import annotations

import json
import hashlib
import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

_log = logging.getLogger("k9log.agents_md_llm")

# ── Anthropic API ─────────────────────────────────────────────────────────────

API_URL = "https://api.anthropic.com/v1/messages"
MODEL   = "claude-sonnet-4-6"

SYSTEM_PROMPT = """You are a security constraint extractor for K9Audit.

Your job: read an AGENTS.md file and extract ALL behavioral constraints into a structured JSON.

Output ONLY valid JSON, no explanation, no markdown fences.

JSON schema:
{
  "deny_content": ["list of strings/patterns that must never appear in tool parameters"],
  "allowed_paths": ["list of allowed file paths or directories (if specified)"],
  "allowed_domains": ["list of allowed network domains (if specified)"],
  "command": {
    "blocklist": ["list of blocked commands or command prefixes"]
  }
}

Rules for extraction:
- "Never run X" or "Do not run X" → command.blocklist: [X]
- "Never modify X file" or "Do not modify X" → deny_content: [X]  
- "Never access /path/" → deny_content: ["/path/"]
- "Only write to X" → allowed_paths: ["X"]
- "Only access X domain" → allowed_domains: ["X"]
- "Never make requests to 192.168.*" → deny_content: ["192.168.", "10.", "127.0.0.1", "localhost"]
- Skip rules that are procedural ("always ask before"), personality ("be helpful"), or coding style
- If a rule lists multiple items with commas, extract each as a separate entry
- Be conservative: when in doubt, include rather than exclude

Output only the JSON object. Nothing else.

CRITICAL PRECISION RULES:
- deny_content must be SHORT SPECIFIC strings: file extensions, paths, IP prefixes
  GOOD: ".env"  "/etc/"  "192.168."  "localhost"
  BAD:  "files containing secrets"  "destructive shell commands"
- If rule says "Never modify X or Y", extract X and Y separately
- command.blocklist must be SHORT COMMAND NAMES only
  GOOD: "rm"  "sudo"  "chmod"
  BAD:  "git commit directly to main"  "destructive shell commands"
- Workflow/process rules like "commit to main" or "ask before deleting" -> SKIP
  These cannot be enforced as string patterns
- allowed_paths must be exact paths like "./projects/" not descriptions
"""


def _call_claude(agents_md_content: str, api_key: str) -> Optional[dict]:
    """Call Claude API to parse AGENTS.md content."""
    import requests

    headers = {
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
        "x-api-key": api_key,
    }

    payload = {
        "model": MODEL,
        "max_tokens": 1024,
        "system": SYSTEM_PROMPT,
        "messages": [
            {
                "role": "user",
                "content": f"Parse this AGENTS.md and extract all constraints:\n\n{agents_md_content}"
            }
        ]
    }

    try:
        resp = requests.post(API_URL, headers=headers, json=payload, timeout=30)
        resp.raise_for_status()
        data = resp.json()
        text = data["content"][0]["text"].strip()
        # Strip markdown fences if present
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        return json.loads(text)
    except Exception as e:
        _log.error("k9log llm_parse: Claude API call failed: %s", e)
        return None


# ── Schema validation ─────────────────────────────────────────────────────────

ALLOWED_KEYS = {"deny_content", "allowed_paths", "allowed_domains", "command"}

def _validate_schema(constraints: dict) -> Tuple[bool, List[str]]:
    """Validate that parsed constraints match the expected schema."""
    errors = []

    if not isinstance(constraints, dict):
        return False, ["Result is not a dict"]

    for key in constraints:
        if key not in ALLOWED_KEYS:
            errors.append(f"Unknown key: {key}")

    for list_key in ("deny_content", "allowed_paths", "allowed_domains"):
        val = constraints.get(list_key)
        if val is not None:
            if not isinstance(val, list):
                errors.append(f"{list_key} must be a list")
            elif not all(isinstance(x, str) for x in val):
                errors.append(f"{list_key} must be a list of strings")

    cmd = constraints.get("command")
    if cmd is not None:
        if not isinstance(cmd, dict):
            errors.append("command must be a dict")
        else:
            bl = cmd.get("blocklist")
            if bl is not None and not isinstance(bl, list):
                errors.append("command.blocklist must be a list")

    return len(errors) == 0, errors


# ── Smoke tests ───────────────────────────────────────────────────────────────

def _run_smoke_tests(constraints: dict, original_rules: str) -> Tuple[bool, List[str]]:
    """
    Run deterministic smoke tests against the parsed constraints.
    Tests that rules in the original AGENTS.md actually produce
    the expected violations.
    """
    from k9log.constraints import check_compliance

    y_star_t = {"constraints": constraints, "y_star_meta": {
        "source": "llm_parse", "hash": "", "version": "1.0.0",
        "loaded_at": "", "unconstrained": False
    }}

    failures = []
    passes   = []

    # Generate test cases from original rules
    test_cases = _derive_test_cases(original_rules, constraints)

    for description, params, should_violate in test_cases:
        result = check_compliance(params, {"result": None}, y_star_t)
        passed = result.get("passed", True)

        if should_violate and passed:
            failures.append(f"MISSED: '{description}' should be VIOLATION but was PASS")
        elif not should_violate and not passed:
            violations = result.get("violations", [])
            msgs = "; ".join(v.get("message", "") for v in violations)
            failures.append(f"FALSE POSITIVE: '{description}' should be PASS but was VIOLATION ({msgs})")
        else:
            passes.append(description)

    return len(failures) == 0, failures


def _derive_test_cases(original_rules: str, constraints: dict) -> List[Tuple[str, dict, bool]]:
    """
    Derive smoke test cases from the original rules and parsed constraints.
    Returns list of (description, params, should_violate).
    """
    cases = []

    # Test each deny_content entry
    for pattern in constraints.get("deny_content", []):
        if len(pattern) > 2:  # Skip trivially short patterns
            cases.append((
                f"deny_content '{pattern}'",
                {"file_path": f"/tmp/{pattern}/test.txt"},
                True  # should violate
            ))

    # Test each command blocklist entry
    for cmd in constraints.get("command", {}).get("blocklist", []):
        if len(cmd) > 1:
            cases.append((
                f"blocklist '{cmd}'",
                {"command": f"{cmd} -rf /tmp/test"},
                True  # should violate
            ))

    # Test allowed_paths: safe path should PASS
    for safe_path in constraints.get("allowed_paths", []):
        if safe_path:
            cases.append((
                f"allowed_path '{safe_path}' (safe)",
                {"file_path": f"{safe_path.rstrip('/')}/test.py"},
                False  # should NOT violate
            ))

    # Test allowed_domains: allowed domain should PASS
    for domain in constraints.get("allowed_domains", []):
        if domain:
            cases.append((
                f"allowed_domain '{domain}' (safe)",
                {"url": f"https://{domain}/api/data"},
                False  # should NOT violate
            ))

    return cases


# ── Result dataclass ──────────────────────────────────────────────────────────

@dataclass
class ParseResult:
    """Result of LLM-assisted AGENTS.md parsing."""
    constraints:     Dict[str, Any]
    verified:        bool
    schema_errors:   List[str]     = field(default_factory=list)
    test_failures:   List[str]     = field(default_factory=list)
    test_passes:     List[str]     = field(default_factory=list)
    constraint_hash: str           = ""
    source_path:     Optional[str] = None
    fallback_used:   bool          = False

    def __post_init__(self):
        if self.constraints:
            canonical = json.dumps(self.constraints, sort_keys=True, ensure_ascii=True)
            self.constraint_hash = "sha256:" + hashlib.sha256(
                canonical.encode()).hexdigest()

    def save(self, skill_name: str = "_agents_md") -> Path:
        """
        Save verified constraints to ~/.k9log/config/{skill_name}.json
        so load_constraints() can find them automatically.
        """
        config_dir = Path.home() / ".k9log" / "config"
        config_dir.mkdir(parents=True, exist_ok=True)
        config_file = config_dir / f"{skill_name}.json"
        config_file.write_text(json.dumps({
            "skill":       skill_name,
            "constraints": self.constraints,
            "version":     "1.0.0",
            "_source":     "llm_parse",
            "_hash":       self.constraint_hash,
            "_verified":   self.verified,
        }, indent=2, ensure_ascii=False), encoding="utf-8")
        return config_file

    def print_summary(self) -> None:
        """Print a human-readable summary of the parse result."""
        from rich.console import Console
        from rich.table import Table
        console = Console()

        status = "[green]✅ VERIFIED[/green]" if self.verified else "[red]❌ FAILED VERIFICATION[/red]"
        console.print(f"\n[bold]K9Audit AGENTS.md Parser[/bold] — {status}\n")

        if self.source_path:
            console.print(f"  Source: {self.source_path}")
        if self.fallback_used:
            console.print("  [yellow]Note: LLM unavailable, used deterministic parser as fallback[/yellow]")

        console.print(f"  Hash:   {self.constraint_hash[:32]}...\n")

        # Show constraints
        table = Table(title="Parsed Constraints", show_header=True)
        table.add_column("Type", style="cyan")
        table.add_column("Values")

        for item in self.constraints.get("deny_content", []):
            table.add_row("deny_content", item)
        for item in self.constraints.get("allowed_paths", []):
            table.add_row("allowed_paths", item)
        for item in self.constraints.get("allowed_domains", []):
            table.add_row("allowed_domains", item)
        for item in self.constraints.get("command", {}).get("blocklist", []):
            table.add_row("command.blocklist", item)

        console.print(table)

        if self.test_failures:
            console.print("\n[red]Smoke test failures:[/red]")
            for f in self.test_failures:
                console.print(f"  ❌ {f}")
        if self.test_passes:
            console.print(f"\n[green]Smoke tests passed: {len(self.test_passes)}[/green]")


# ── Public API ────────────────────────────────────────────────────────────────



def _extract_raw_rules(text):
    rules = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith(("- ", "* ", "+ ")):
            r = s.lstrip("-*+ ").strip()
            if len(r) > 10:
                rules.append(r)
    return rules

def _check_coverage(raw_rules, constraints, api_key, base_url, model):
    if not raw_rules:
        return []
    import json as _j
    prompt = "Check which rules are NOT covered in the constraints.\nRules:\n" + _j.dumps(raw_rules) + "\nConstraints:\n" + _j.dumps(constraints) + "\nReturn ONLY a JSON array of uncovered rules. If all covered return []."
    result = _call_claude(prompt, api_key)
    if isinstance(result, list):
        return result
    return []

def _fix_missing(missing, constraints, api_key, base_url, model):
    import json as _j
    prompt = "Add these missing rules to constraints JSON.\nMissing:\n" + _j.dumps(missing) + "\nExisting:\n" + _j.dumps(constraints) + "\nReturn ONLY the complete updated JSON."
    return _call_claude(prompt, api_key)

def parse_with_coverage_check(text, api_key, base_url="https://api.anthropic.com", model="", max_retries=2):
    raw_rules = _extract_raw_rules(text)
    _log.info("coverage: found %d raw rules", len(raw_rules))
    constraints = _call_claude(text, api_key)
    if not constraints:
        return None, {"total_rules": len(raw_rules), "covered": 0, "missing_after_fix": raw_rules, "retries": 0}
    missing = []
    retries = 0
    for attempt in range(max_retries):
        missing = _check_coverage(raw_rules, constraints, api_key, base_url, model)
        _log.info("coverage attempt %d: %d missing", attempt+1, len(missing))
        if not missing:
            break
        fixed = _fix_missing(missing, constraints, api_key, base_url, model)
        if fixed and isinstance(fixed, dict):
            constraints = fixed
            retries += 1
        else:
            break
    covered = len(raw_rules) - len(missing)
    return constraints, {"total_rules": len(raw_rules), "covered": covered,
                         "coverage_pct": round(covered/len(raw_rules)*100) if raw_rules else 100,
                         "missing_after_fix": missing, "retries": retries}

def parse_agents_md_with_llm(
    filepath: str | Path,
    api_key:  Optional[str] = None,
    save:     bool = False,
    skill_name: str = "_agents_md",
) -> ParseResult:
    """
    Parse AGENTS.md using Claude, then verify with deterministic tests.

    Args:
        filepath:   Path to AGENTS.md or CLAUDE.md
        api_key:    Anthropic API key. If None, reads ANTHROPIC_API_KEY env var.
        save:       If True and verified, auto-save to ~/.k9log/config/
        skill_name: Config file key for saving (default: _agents_md)

    Returns:
        ParseResult with constraints, verification status, and test results.
    """
    path = Path(filepath).expanduser()
    if not path.exists():
        return ParseResult(
            constraints={}, verified=False,
            schema_errors=[f"File not found: {path}"]
        )

    content = path.read_text(encoding="utf-8", errors="replace")

    # Get API key
    key = api_key or os.environ.get("ANTHROPIC_API_KEY", "")

    constraints = None
    fallback_used = False

    if key:
        constraints, coverage = parse_with_coverage_check(content, key)
        if coverage: _log.info("coverage result: %s", coverage)

    if constraints is None:
        # Fallback to deterministic parser
        _log.warning("k9log llm_parse: LLM unavailable, falling back to pattern matcher")
        from k9log.agents_md_parser import parse_agents_md_to_constraints
        constraints = parse_agents_md_to_constraints(path)
        fallback_used = True

    if not constraints:
        return ParseResult(
            constraints={}, verified=False, fallback_used=fallback_used,
            schema_errors=["No constraints extracted"],
            source_path=str(path)
        )

    # Step 1: Schema validation
    schema_ok, schema_errors = _validate_schema(constraints)

    # Step 2: Smoke tests
    test_ok, test_failures = _run_smoke_tests(constraints, content)
    test_passes = []  # populated by smoke tests

    verified = schema_ok and test_ok

    result = ParseResult(
        constraints=constraints,
        verified=verified,
        schema_errors=schema_errors,
        test_failures=test_failures,
        source_path=str(path),
        fallback_used=fallback_used,
    )

    if save and verified:
        saved_path = result.save(skill_name)
        _log.info("k9log llm_parse: saved verified constraints to %s", saved_path)

    return result
